# Generated by Django 5.0.6 on 2024-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pregunta_1', models.IntegerField()),
                ('pregunta_2', models.IntegerField()),
                ('pregunta_3', models.IntegerField()),
                ('pregunta_4', models.IntegerField()),
                ('pregunta_5', models.IntegerField()),
                ('pregunta_6', models.IntegerField()),
                ('pregunta_7', models.IntegerField()),
                ('pregunta_8', models.IntegerField()),
                ('pregunta_9', models.CharField(max_length=100)),
                ('pregunta_10', models.CharField(max_length=100)),
                ('pregunta_11', models.CharField(max_length=100)),
                ('pregunta_12', models.CharField(max_length=100)),
                ('pregunta_13', models.CharField(max_length=100)),
                ('pregunta_14', models.CharField(max_length=100)),
                ('pregunta_15', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
    ]
